spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SpringBoot-book?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: @jzq1520
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true